# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ting Lu
description: > # this means to ignore newlines until "baseurl:"
  A Developer interested in Programming Languages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lisalu.com.au" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: lisatinglu
github_username:  tinglu
# codepen_username: lisatinglu
twitter_username: lisatinglu

google_analytics: UA-31132044-2

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["Gemfile", "Gemfile.lock", node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Outputting
permalink:  /:title

# Build settings
markdown:    kramdown
kramdown:
    input:   GFM
    syntax_highlighter: rouge
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

# Jekyll Tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
ignored_tags: [tags,to,ignore]
tag_page_data:
  sitemap: false

# Disqus Comments
#disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
#    shortname: tinglu